name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        scheme: ["Development"]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
    
    - name: List available simulators
      run: xcrun simctl list devices available
    
    - name: Build and Test
      env:
        SCHEME: ${{ matrix.scheme }}
      run: |
        # Extract the name and OS version of the first available simulator
        DEVICE=$(xcrun simctl list devices available | grep -E '\((.*)\) \((.*)\) ' | head -n 1 | awk -F "[()]" '{print $2}' | awk '{print $1}')
        OS_VERSION=$(xcrun simctl list devices available | grep -E '\((.*)\) \((.*)\) ' | head -n 1 | awk -F "[()]" '{print $4}' | awk '{print $1}')
        
        echo "Selected Device: $DEVICE ($OS_VERSION)"
        
        xcodebuild build-for-testing -scheme "$SCHEME" -destination "platform=iOS Simulator,name=$DEVICE,OS=$OS_VERSION" -workspace "NewsApp.xcworkspace"
