name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        scheme: ["Development"]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Xcode version
      run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
    
    - name: List available simulators
      run: xcrun simctl list devices available
    
    - name: Build and Test
      env:
        SCHEME: ${{ matrix.scheme }}
      run: |
        DEVICE="5DDD29C5-6A31-42EB-B32B-BDAFF88BCFB"
        echo "Selected Device: $DEVICE"
    
        xcodebuild build-for-testing -scheme "$SCHEME" -destination "platform=iOS Simulator,id=$DEVICE" -workspace "NewsApp.xcworkspace"
        xcodebuild test-without-building -scheme "$SCHEME" -destination "platform=iOS Simulator,id=$DEVICE" -workspace "NewsApp.xcworkspace"
